language: csharp
solution: ScratchEVTCParser.sln
mono:
  - latest

before_deploy:
  - mkdir artifacts
  - cp -R ArcdpsLogManager/bin/Release/net472 artifacts/ArcdpsLogManager
  - cp -R EVTCInspector/bin/Release/net472 artifacts/EVTCInspector
  - cd artifacts
  - zip -r ArcdpsLogManager.zip ArcdpsLogManager
  - zip -r EVTCInspector.zip EVTCInspector

deploy:
  provider: releases
  api_key:
    secure: nHq+ynn1hqmENAVfag533qEfsqw/+JwZe9Sjssdcj9Jpr8v9m096xV4DLQKGEbJY4zVQXgFFEeDyAA1yZZm2Z8qbZDJSYhGBc+qwyB1TyiXD2vhmZW8UaGe4muIVd7O3bK2Zap674AidAtL2ax8eQfFnFYfFkEtOStfGhJClQS2/efKgsH8o6SPM42dCLe0ov3Xd+HTOmCx8fcczKxdraZ4lK7ENM20WGwaXRV/EwjJEANHQZ8b4CyYP5L377gWeghcbvuCGR9ASkE3dTmSauxQ0xYBWy17ggnSXiQlfS2DSnkA4BICV5JTDbRYb8auaZ9CFwBJvQEx9UQClz6ZfELn7IusuJEl0+3sIQ+1bCNM0rhFsbZ4TLlUeDv6YDIxv/J2PaHHgwxgywmeKSys0ScQBKhm7qdQfZ00Fq+ZDRQbiDmsCiwxpR+dwwsuXq8ByfNjnP8S4jptiDJWC6EQtaQH/kSt2qo147yg4fViCsToh0p/RzELmwqN9jQLGqRYP6d3yANd3O5eDA0v+JMqnz8wnAslyI+wRfBNjGwwQk1A6bIsv1w6dGNL7kQ92kkc2CuCxAhUCIBfsW7fNlVSmwwIqrZt/au1YWVzsYuv1LtSjLIupEMDs/2IFD/aiYwDr2wHj1x9VuD2vuv2k4aOgyQZZTkQPz5Ra+vdFmYwnNhA=
  file: 
    - "ArcdpsLogManager.zip"
    - "EVTCInspector.zip"
  skip_cleanup: true
  draft: true
  on:
    tags: true
    repo: gw2scratch/evtc
