name: Build and test (.NET Core)

on:
  push:
    branches: [ master, netcore ]
  pull_request:
    branches: [ master, netcore ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Package Log Manager (Windows, WPF)
      run: dotnet publish ArcdpsLogManager.Wpf --configuration Release -r win-x64 --self-contained=false -p:PublishSingleFile=true -o artifacts/win64/
    - name: Package Log Manager (Windows, WPF, self-contained)
      run: dotnet publish ArcdpsLogManager.Wpf --configuration Release -r win-x64 --self-contained=true -p:PublishSingleFile=true -o artifacts/win64-sc/
    - name: Package Log Manager (Linux, GTK)
      run: dotnet publish ArcdpsLogManager.Gtk --configuration Release -r linux-x64 --self-contained=false -p:PublishSingleFile=true -o artifacts/linux64/
    - name: Package Log Manager (Linux, GTK, self-contained)
      run: dotnet publish ArcdpsLogManager.Gtk --configuration Release -r linux-x64 --self-contained=true -p:PublishSingleFile=true -o artifacts/linux64-sc/
    # The PDB files for the self-contained versions should be the same as the non-self-contained version, so we only keep one.
    - name: Bundle PDBs
      run: mkdir artifacts/pdb/
          | mv artifacts/win64/*.pdb artifacts/pdb/
          | mv artifacts/linux64/*.pdb artifacts/pdb/
    - name: Prettify executable filenames
      run: mv artifacts/win64/GW2Scratch.ArcdpsLogManager.Wpf.exe artifacts/win64/ArcdpsLogManager.exe
          | mv artifacts/win64-sc/GW2Scratch.ArcdpsLogManager.Wpf.exe artifacts/win64-sc/ArcdpsLogManager.exe
          | mv artifacts/linux64/GW2Scratch.ArcdpsLogManager.Gtk artifacts/linux64/ArcdpsLogManager
          | mv artifacts/linux64-sc/GW2Scratch.ArcdpsLogManager.Gtk artifacts/linux64-sc/ArcdpsLogManager
    - name: Upload artifact (Windows)
      uses: actions/upload-artifact@v2
      with:
        name: Log Manager (Windows)
        path: artifacts/win64/ArcdpsLogManager.exe
    - name: Upload artifact (Windows, self-contained)
      uses: actions/upload-artifact@v2
      with:
        name: Log Manager (Windows, self-contained)
        path: artifacts/win64-sc/ArcdpsLogManager.exe
    - name: Upload artifact (Linux)
      uses: actions/upload-artifact@v2
      with:
        name: Log Manager (Linux)
        path: artifacts/linux64/ArcdpsLogManager
    - name: Upload artifact (Linux, self-contained)
      uses: actions/upload-artifact@v2
      with:
        name: Log Manager (Linux, self-contained)
        path: artifacts/linux64-sc/ArcdpsLogManager
    - name: Upload artifact (PDB files)
      uses: actions/upload-artifact@v2
      with:
        name: PDB files
        path: artifacts/pdb/
